### ISSUE TITLE
Error occurred while enabling AxEnvoy v1.0.10 (Is it up to date?)

### ISSUE THREAD

**Issue by baaliint** [Artillex-Studios/AxEnvoys#1]
There is a bug with PlaceholderAPI, but if I delete it from the plugins, AxEnvoy works perfectly.
My server version is Purpur 1.19.4

[18:11:59 INFO]: [AxEnvoy] Enabling AxEnvoy v1.0.10
[18:11:59 INFO]: [AxEnvoy] Enabled DecentHolograms hook!
[18:11:59 INFO]: [AxEnvoy] Enabled PlaceholderAPI hook!
[18:11:59 ERROR]: Error occurred while enabling AxEnvoy v1.0.10 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/PlaceholderExpansion
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperSimplePluginClassLoader.findClass(PaperSimplePluginClassLoader.java:103) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:114) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at com.artillexstudios.axenvoy.AxEnvoyPlugin.onEnable(AxEnvoyPlugin.java:53) ~[AxEnvoy-1.0.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.expansion.PlaceholderExpansion
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 21 more

**Comment by AverageGithub** [comment]
What PlaceholderAPI version are you using? The stacktrace doesn't really make sense.

**Comment by baaliint** [comment]
Latest (2.11.5)

**Comment by AverageGithub** [comment]
On 1.20.1 it works fine for me with the version of placeholderapi and axenvoys that you're using. My guess is that something is broken on the last couple versions of 1.19.4 purpur due to the paper plugin system. Removing the paper-plugin.yml from the jar will fix this issue, I guess.
